#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_render_graph = env_modules.Clone()

# Godot source files
env_render_graph.add_source_files(env.modules_sources, "*.cpp")
if env.editor_build:
    env_render_graph.add_source_files(env.modules_sources, "editor/*.cpp")
