#!/usr/bin/env python

Import("env")
Import("env_modules")

env_gameplay = env_modules.Clone()

env_gameplay.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_gameplay.add_source_files(env.modules_sources, "./editor/*.cpp")

if env["tests"]:
    env_gameplay.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_gameplay.add_source_files(env.modules_sources, "./tests/*.cpp")
